"""Generate a standalone HTML report from a scan result dict."""

SEVERITY_ORDER = ["high", "medium", "low", "info"]
SEVERITY_COLOR = {
    "high": "#d64545",
    "medium": "#d98a34",
    "low": "#3a7bd5",
    "info": "#6b7280",
}


def _severity_counts(findings):
    counts = {s: 0 for s in SEVERITY_ORDER}
    for f in findings:
        counts[f.get("severity", "info")] = counts.get(f.get("severity", "info"), 0) + 1
    return counts


def _render_findings_table(findings):
    if not findings:
        return "<p class='empty'>No findings.</p>"
    ordered = sorted(findings, key=lambda f: SEVERITY_ORDER.index(f.get("severity", "info")))
    rows = []
    for f in ordered:
        detail = f.get("detail", "")
        if isinstance(detail, (list, dict)):
            import json
            detail = f"<pre>{json.dumps(detail, indent=2)[:2000]}</pre>"
        color = SEVERITY_COLOR.get(f.get("severity", "info"), "#6b7280")
        rows.append(f"""
        <tr>
          <td><span class="badge" style="background:{color}">{f.get('severity','info').upper()}</span></td>
          <td>{f.get('check','')}</td>
          <td>{f.get('message','')}</td>
          <td class="detail">{detail}</td>
        </tr>""")
    return f"""
    <table>
      <thead><tr><th>Severity</th><th>Check</th><th>Message</th><th>Detail</th></tr></thead>
      <tbody>{''.join(rows)}</tbody>
    </table>"""


def build_html_report(scan):
    """
    scan: dict with keys url, started_at, finished_at,
          security_findings, functionality_findings, functionality_summary
    """
    sec_counts = _severity_counts(scan["security_findings"])
    func_counts = _severity_counts(scan["functionality_findings"])

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Scan report \u2014 {scan['url']}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 0; background: #f7f8fa; color: #1a1d23; }}
  header {{ background: #14161a; color: #fff; padding: 32px 40px; }}
  header h1 {{ margin: 0 0 6px; font-size: 22px; }}
  header p {{ margin: 0; color: #9aa1ac; font-size: 13px; }}
  .container {{ max-width: 1100px; margin: 0 auto; padding: 32px 40px; }}
  .summary {{ display: flex; gap: 16px; margin-bottom: 32px; flex-wrap: wrap; }}
  .card {{ background: #fff; border-radius: 10px; padding: 16px 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); min-width: 140px; }}
  .card .num {{ font-size: 28px; font-weight: 700; }}
  .card .label {{ font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: .04em; }}
  h2 {{ font-size: 18px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; margin-top: 40px; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; }}
  th, td {{ text-align: left; padding: 10px 12px; font-size: 13px; border-bottom: 1px solid #eef0f2; vertical-align: top; }}
  th {{ background: #f1f2f4; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: #6b7280; }}
  .badge {{ color: #fff; font-size: 11px; font-weight: 600; padding: 3px 8px; border-radius: 4px; white-space: nowrap; }}
  .detail pre {{ margin: 0; font-size: 11px; white-space: pre-wrap; max-height: 160px; overflow: auto; }}
  .empty {{ color: #6b7280; font-style: italic; }}
  footer {{ padding: 24px 40px; font-size: 12px; color: #9aa1ac; }}
</style>
</head>
<body>
<header>
  <h1>Scan report</h1>
  <p>{scan['url']} &nbsp;\u2022&nbsp; started {scan['started_at']} &nbsp;\u2022&nbsp; finished {scan['finished_at']}</p>
</header>
<div class="container">
  <div class="summary">
    <div class="card"><div class="num">{sec_counts['high']}</div><div class="label">High (security)</div></div>
    <div class="card"><div class="num">{sec_counts['medium']}</div><div class="label">Medium (security)</div></div>
    <div class="card"><div class="num">{scan['functionality_summary']['pages_crawled']}</div><div class="label">Pages crawled</div></div>
    <div class="card"><div class="num">{scan['functionality_summary']['forms_found']}</div><div class="label">Forms found</div></div>
  </div>

  <h2>Security findings</h2>
  {_render_findings_table(scan['security_findings'])}

  <h2>Functionality findings</h2>
  {_render_findings_table(scan['functionality_findings'])}
</div>
<footer>Generated by WebTester \u2014 for use only on sites you own or are explicitly authorized to test.</footer>
</body>
</html>"""
    return html
